name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare workspace
      run: mkdir workspace
    - name: Build the WireGuard binary (wireguard-go)
      run: |
        cat build-wg-go.sh | docker run --rm -i -v="$PWD/workspace:/workspace" -w="/workspace" golang:latest sh
        ls ./workspace/wireguard-go*
    - name: Get version
      id: getver
      run: ./workspace/wireguard-go --version | head -n 1 | cut -d ' ' -f 2
